deploy_www:
  stage: deploy
  script:
    - chmod uog+x bin/*
    - sudo -EHu www_deploy bin/ci_deploy_www.sh
  tags:
    - www
  only:
    - master

deploy_wwwtest:
  stage: deploy
  script:
    - chmod uog+x bin/*
    - sudo -EHu www_deploy bin/ci_deploy_www.sh
  tags:
    - wwwtest
  only:
    - test

deploy_wwwdev:
  stage: deploy
  script:
    - chmod uog+x bin/*
    - sudo -EHu www_deploy bin/ci_deploy_www.sh
  tags:
    - wwwdev
  only:
    - dev
