deploy_www:
  stage: deploy
  script:
    - chmod uog+x bin/*
    - sudo -EHu banner bin/ci_deploy.sh
  tags:
    - www
  only:
    - master
deploy_wwwtest:
  stage: deploy
  script:
    - chmod uog+x bin/*
    - sudo -EHu banner bin/ci_deploy.sh
  tags:
    - wwwtest
  only:
    - test
deploy_wwwdev:
  stage: deploy
  script:
    - chmod uog+x bin/*
    - sudo -EHu banner bin/ci_deploy.sh
  tags:
    - wwwdev
  only:
    - dev


